# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.16.6
minimal_mistakes_skin: contrast

# Site settings
title: iBossOrg
title_separator: "|"
subtitle: # site tagline that appears below site title in masthead
name: iBossOrg
# description: >- # this means to ignore newlines
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
teaser: # path of fallback teaser image
logo: # path of logo image to display in the masthead
breadcrumbs: false
search: true
search_full_content: true
# google_site_verification: # SEO Related

# Social sharing
# Analytics
# Site author

# Site footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/iBossOrg

# Reading files
include:
  - .htaccess
  - _pages
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - docker-compose.yml
encoding: utf-8
keep_files:
  - .git

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
# Sass/SCSS

# Outputting
paginate_path: /page:num/
paginate: 5 # amount of posts to show
permalink: /:categories/:title/
timezone: Europe/Prague

# Plugins
plugins:
  - github-pages
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
